package ru.hse.fmcs.Parsing;

import Parsing.Lexer;
import Parsing.Parser;
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.SymbolFactory;
import ru.hse.fmcs.Parsing.ASTNode.ASTNode;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.io.InputStreamReader;

/**
 * @author sergey
 * <p>
 * Files generated by CUP located in wrong package. It is
 * a bug of that parser.
 */
public class ASTBuilder {
  /**
   * Parser implementation using for parsing.
   */
  private final Parser parser;

  public ASTBuilder(final String cmd) {
    this(new ByteArrayInputStream(cmd.getBytes()));
  }

  public ASTBuilder(final InputStream is) {
    final SymbolFactory sf = new ComplexSymbolFactory();
    final Lexer lexer = new Lexer(new InputStreamReader(is), sf);
    parser = new Parser(lexer, sf);
  }

  public AST build() throws ParsingException {
    ASTNode root;
    try {
      root = (ASTNode) parser.parse().value;
    } catch (Exception e) {
      throw new ParsingException(e.getMessage());
    }
    return new AST(root);
  }
}
